name: p2p
description: A starting point for Dart libraries or applications.
version: 0.0.1-dev
homepage: https://github.com/privacent/p2p
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  ulid:

dev_dependencies:
  test: ^0.12.0
